services:
  php-fpm:
    # sesuaikan php ini
    image: tongkolspace/php-fpm-moodle:${IMAGE_MOODLE_VERSION}
    container_name: php-fpm-moodle-${APP_NAME}
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - IMAGE_MOODLE_VERSION=${IMAGE_MOODLE_VERSION}
    env_file:
      - .env-dev-local
    environment:
      TZ: ${TZ}
    volumes:
      - ../moodle:/var/www/html
      - ../moodledata:/var/www/moodledata
      - ../moodle_mod:/var/www/moodle_mod
      - ./php-fpm/php-dev.ini:/usr/local/etc/php/conf.d/zz-custom-php.ini
      - ./php-fpm/php-fpm-dev.conf:/usr/local/etc/php-fpm.d/easyengine.conf  
    networks:
      - internal
      - external
  nginx:
    image: tongkolspace/nginx-ee:v1.0.2
    container_name: nginx-moodle-${APP_NAME}
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ../admin:/var/www/admin
      - ../moodle:/var/www/html
      - ../moodledata:/var/www/moodledata
      - ../moodle_mod:/var/www/moodle_mod
      - ./nginx/sites-enabled/admin-dev.conf:/etc/nginx/sites-enabled/admin.conf
      - ./nginx/sites-enabled/moodle.conf:/etc/nginx/sites-enabled/default
      - ./nginx/log:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/common-extra:/etc/nginx/common-extra
      - ./nginx/conf.d-extra:/etc/nginx/conf.d-extra
      - ./nginx/conf.d/cloudflare.conf:/etc/nginx/conf.d/cloudflare.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/tmp/nginx:/tmp/nginx
    depends_on:
      - redis
    networks:
      - internal
      - external
    environment:
      TZ: ${TZ}
    ports:
      - 80:80
      - 57710:57710
  redis:
    image: redis:latest
    container_name: redis-moodle-${APP_NAME}
    restart: unless-stopped
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      TZ: ${TZ}
    networks:
      - internal
  workspace-moodle:
    image: tongkolspace/workspace-moodle:${IMAGE_MOODLE_VERSION}
    container_name: workspace-moodle-${APP_NAME}
    build:
      context: ../
      dockerfile: ./docker/workspace/Dockerfile
      args:
        - IMAGE_MOODLE_VERSION=${IMAGE_MOODLE_VERSION}
    volumes:
      - ./php-fpm/php-dev.ini:/usr/local/etc/php/conf.d/zz-custom-php.ini
      - ../moodle:/var/www/html
      - ../moodledata:/var/www/moodledata
      - ../moodle_mod:/var/www/moodle_mod
    env_file:
      - .env-dev-local
    environment:
      TZ: "${TZ}"
    networks:
      - internal
      - external
    # ports:
      # Bakend Laravel
      # - 8000:8000
      # - 5173:5173
  supervisor:
    image: tongkolspace/supervisor-moodle:${IMAGE_MOODLE_VERSION}
    container_name: supervisor-moodle-${APP_NAME}
    build:
      context: ../
      dockerfile: ./docker/supervisor/Dockerfile
      args:
        - IMAGE_MOODLE_VERSION=${IMAGE_MOODLE_VERSION}
    volumes:
      - ./php-fpm/php-dev.ini:/usr/local/etc/php/conf.d/zz-custom-php.ini
      - ../moodle:/var/www/html
      - ../moodledata:/var/www/moodledata
      - ../moodle_mod:/var/www/moodle_mod
      - ./supervisor/cron/cronjob-moodle:/tmp/cronjob
      - ./supervisor/supervisor.conf/supervisor-cron.conf:/etc/supervisor/conf.d/supervisor-cron.conf
    env_file:
      - .env-dev-local
    environment:
      TZ: "${TZ}"
    networks:
      - internal
      - external
  db:
    image: mariadb:11.4.2
    container_name: db-moodle-${APP_NAME}
    restart: unless-stopped
    # ports:
    # Uncomment jika tidak ingin ekpsose
    # - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}       
      MYSQL_USER: "${DB_USERNAME}"               
      MYSQL_PASSWORD: "${DB_PASSWORD}"       
      TZ: ${TZ}
    volumes:
      - ./mysql/config/mysql-dev.cnf:/etc/my.cnf
      - ./mysql/datadir:/var/lib/mysql
    networks:
      - internal
      - external
  pma:
    # Akses dengan http://domain/pma/ (wajib dengan slash)
    image: phpmyadmin/phpmyadmin
    container_name: pma-moodle-${APP_NAME}
    restart: unless-stopped
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      UPLOAD_LIMIT: 50M
      PMA_ABSOLUTE_URI: "http://${DOMAIN_MOODLE}/pma/"
    links:
      - db:db
    networks:
      - internal
  redis-commander:
    container_name: redis-commander-moodle-${APP_NAME}
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: unless-stopped
    environment:
    - REDIS_HOSTS=local:redis:6379
    networks:
      - internal
networks:
  internal:
    name: ${APP_NAME}-${NETWORK}
  external:
    external: true
    name: ${NETWORK}