services:
  moodle:
    image: app-moodle-${APP_NAME}:${APP_TAG} 
    container_name: moodle-dev-tongkolspace-${APP_NAME}
    ports: !reset 
    volumes: !override
      # Moodle
      - ../moodle:/var/www/html
      - ../moodle_mod:/var/www/moodle_mod
      - ../moodledata:/var/www/moodledata
      - ./app/nginx/sites-available/admin.conf:/etc/nginx/sites-enabled/admin.conf
      # PHP 
      - ./app/php-fpm/php-fpm-prod.conf:/etc/php82/php-fpm.d/www.conf
      - ./app/php-fpm/php-prod.ini:/etc/php82/conf.d/custom.ini
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.moodle-${APP_NAME}.tls=true"
      - "traefik.http.routers.moodle-${APP_NAME}.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.routers.moodle-${APP_NAME}.rule=Host(`${DOMAIN_MOODLE}`)"
      - "traefik.http.routers.moodle-${APP_NAME}.entrypoints=web,websecure"
      - "traefik.http.routers.moodle-${APP_NAME}.service=moodle-${APP_NAME}"
      - "traefik.http.services.moodle-${APP_NAME}.loadbalancer.server.port=8000"
      - "traefik.http.routers.moodle-admin-${APP_NAME}.tls=true"
      - "traefik.http.routers.moodle-admin-${APP_NAME}.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.routers.moodle-admin-${APP_NAME}.rule=Host(`${DOMAIN_MOODLE}`)"
      - "traefik.http.routers.moodle-admin-${APP_NAME}.entrypoints=admin"
      - "traefik.http.routers.moodle-admin-${APP_NAME}.service=moodle-admin-${APP_NAME}"
      - "traefik.http.services.moodle-admin-${APP_NAME}.loadbalancer.server.port=57710"
      - "traefik.docker.network=${NETWORK}"
    env_file:
      - .env-dev-local
    networks:
      - internal
      - external
  redis:
    volumes: !override
      - ./redis/redis-prod.conf:/usr/local/etc/redis/redis.conf
  db:
    volumes: !override
      - ./mysql/datadir:/var/lib/mysql
      - ./mysql/config/mysql-prod.cnf:/etc/my.cnf