services:
  moodle:
    image: app-moodle-${APP_NAME}:${APP_TAG} 
    container_name: moodle-dev-local-${APP_NAME}
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - ROLE_BACKGROUND=true
      - ROLE_NGINX=true
      - ROLE_PHP_FPM=true
    env_file:
      - .env-dev-local
    ports:
      - 80:8000
      - 57710:57710
    networks:
      - internal
      - external
    volumes: 
      # Moodle
      - ../moodle:/var/www/html
      - ../moodle_mod:/var/www/moodle_mod
      - ../moodledata:/var/www/moodledata
      # Nginx
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/nginx/common:/etc/nginx/common
      - ./app/nginx/conf.d:/etc/nginx/conf.d
      - ./app/nginx/sites-available:/etc/nginx/sites-available
      - ./app/nginx/sites-available/moodle.conf:/etc/nginx/sites-enabled/moodle.conf
      - ./app/nginx/snippets:/etc/nginx/snippets
      - ./app/nginx/empty:/etc/nginx/empty
      # Admin Panel
      - ../admin:/var/www/admin
      - ./app/nginx/sites-available/admin.conf:/etc/nginx/sites-enabled/admin.conf
      # PHP 
      - ./app/php-fpm/php-fpm-dev.conf:/etc/php82/php-fpm.d/www.conf
      - ./app/php-fpm/php-dev.ini:/etc/php82/conf.d/custom.ini
      # supervisor & cron
      - ./app/supervisor/conf.d:/home/app/supervisor/conf.d
      - ./app/cron:/home/app/cron
      # entrypoint
      - ./app/entrypoint.sh:/usr/local/bin/entrypoint.sh
  db:
    image: mariadb:11.4.2
    container_name: db-moodle-${APP_NAME}
    restart: unless-stopped
    # ports:
    # Uncomment jika tidak ingin ekpsose
    # - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}       
      MYSQL_USER: "${DB_USERNAME}"               
      MYSQL_PASSWORD: "${DB_PASSWORD}"       
      TZ: ${TZ}
    volumes:
      - ./mysql/config/mysql-dev.cnf:/etc/my.cnf
      - ./mysql/datadir:/var/lib/mysql
    networks:
      - internal
      - external
  pma:
    # Akses dengan http://domain/pma/ (wajib dengan slash)
    image: phpmyadmin/phpmyadmin
    container_name: pma-moodle-${APP_NAME}
    restart: unless-stopped
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      UPLOAD_LIMIT: 50M
      PMA_ABSOLUTE_URI: "http://${DOMAIN_MOODLE}/pma/"
    links:
      - db:db
    networks:
      - internal
  redis:
    image: redis:latest
    container_name: redis-moodle-${APP_NAME}
    restart: unless-stopped
    volumes:
      - ./redis/redis-dev.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      TZ: ${TZ}
    networks:
      - internal
  redis-commander:
    container_name: redis-commander-moodle-${APP_NAME}
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: unless-stopped
    environment:
    - REDIS_HOSTS=local:redis:6379
    networks:
      - internal
networks:
  internal:
    name: ${APP_NAME}-${NETWORK}
  external:
    external: true
    name: ${NETWORK}