ARG IMAGE_MOODLE_VERSION
FROM tongkolspace/belmawa-php-fpm-moodle:${IMAGE_MOODLE_VERSION}
LABEL maintainer="Todi Adiyatmo <todiadiyatmo@gmail.com>"
LABEL org.label-schema.vendor="Tongkolspace"
LABEL org.label-schema.name="workspace"

USER  workspace
WORKDIR  /var/www/html
CMD []